devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
  "iPhone 16",
  "iPhone 15 Pro Max",
  "iPhone 15"
])

languages([
  "en-US"
])

scheme "ElectriciansNow"
output_directory "./fastlane/screenshots"
clear_previous_screenshots true
